- name: configuring backed
  hosts: backend
  become: yes
  tasks:
  - name: disable nodedjs
    ansible.builtin.command:
      dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command:
      dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: creating expense user
    ansible.builtin.user:
      name: expense

  - name: Create a directory app
    ansible.builtin.file:
      path: /app
      state: directory