- name: configuring backed
  hosts: backend
  become: yes
  tasks:
  - name: disable nodedjs
    ansible.builtin.command:
      dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command:
      dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: creating expense user
    ansible.builtin.user:
      name: expense

  - name: Create a directory app
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download backed code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: unzip file
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app

  - name: Install npm depedencies
    community.general.npm:
      name: npm
      path: /app
  
  - name: install python libs
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

    - name: import mysql data
      community.mysql.mysql_db:
        state: import
        name: all
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql.srikanthannam.space
        target: /app/schema/backend.sql
    
    - name: daemon reload and restart service
      ansible.builtin.systemd_service:
        enabled: true
        state: restarted
        daemon_reload: true
        name: backend
    
    
