- name: configure frontend server
  hosts: frontend
  become: yes

  tasks:
    - name: install nginx
      ansible.builtin.command: dnf install nginx -y
    - name: start mysql service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent
