- name: configure frontend server
  hosts: frontend
  become: yes

  tasks:
    - name: install nginx
      ansible.builtin.command: dnf install nginx -y
    - name: start mysql service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent
    - name: Download frontend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip

    - name: unzip the frontend code
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes
